FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt install fish -y
RUN apt install git -y 
RUN apt install gcc g++ -y
RUN apt install norminette -y
RUN git clone https://github.com/SMOSTAFAH1/francinette-installer